### ISSUE TITLE
errors from flutter build web 

### ISSUE THREAD

**Issue by goodforever** [theshivamlko/navoki_notes#4]
Target dart2js failed: Exception: lib/screen/LoginPage.dart:502:9:
Error: No named parameter with the name 'child'.
        child: AlertDialog(
        ^^^^^
../../../flutter/packages/flutter/lib/src/material/dialog.dart:1016:12:
Info: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
Error: Compilation failed.

**Comment by theshivamlko** [comment]
[SOLVED] Updated Flutter 2.10
